# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b4936cc944f48039d29cdf1b7789df30abab54757ceb64410201607a17f904ad46e63ad74787d36000998ec620e43bf7f0710195bc5f170e4f807acfc9998ac

test:
  secret_key_base: 32b3669647dadab74a81e38ccc55430ad40ad7844f3276c45b841c4b8bc3a22069ac0e54b23a9a1afe2be5eb585d269cbd0bd44cd1daa48e24eee58003da2e56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
